clear; clc;
b0=2;
figure('Color','w'); 
nois_i=0; nois_o=0; sim('Task_C_mod',2);
subplot(1,2,1); hold on;
plot(u.time,u.data,'--','Color','black','LineWidth',2);
plot(x.time,x.data,'-','Color','black','LineWidth',2); ylim([0,5]);
FormatCharts('$$t,{\textrm s}$$','$$u(t), x(t)$$','without noises');
legend('{\it u}({\it t})','{\it x}({\it t})');
nois_i=1; nois_o=1; sim('Task_C_mod',2);
subplot(1,2,2); hold on;
plot(u.time,u.data,'--','Color','black','LineWidth',2);
plot(x.time,x.data,'-','Color','black','LineWidth',2); ylim([0,5]);
FormatCharts('$$t,{\textrm s}$$','$$u(t), x(t)$$','with noises');
legend('{\it u}({\it t})','{\it x}({\it t})');
b0_id=0; stk4=0;
for k=1:1:length(x.data);
    b0_id=b0_id+x.data(k)*x.time(k)^2;
    stk4=stk4+x.time(k)^4;
end;
b0_id=b0_id/stk4;
format longe; disp(b0_id);
